// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByhRadsvPQyqsnhqBMQG4aJNg9F05ePWM',
    appId: '1:1054221680598:web:ecdc46b2515f31f06cae77',
    messagingSenderId: '1054221680598',
    projectId: 'yourturn-6c6b1',
    authDomain: 'yourturn-6c6b1.firebaseapp.com',
    storageBucket: 'yourturn-6c6b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_GUYmPqPRH_gs28TNdikD_16gPGtyev4',
    appId: '1:1054221680598:android:7274fe3e9944e29b6cae77',
    messagingSenderId: '1054221680598',
    projectId: 'yourturn-6c6b1',
    storageBucket: 'yourturn-6c6b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB7W8pVUA6P6wh7GxnfGJmyiY_A6hdGGI',
    appId: '1:1054221680598:ios:7bfed86b7d36edab6cae77',
    messagingSenderId: '1054221680598',
    projectId: 'yourturn-6c6b1',
    storageBucket: 'yourturn-6c6b1.firebasestorage.app',
    iosBundleId: 'com.example.yourturn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB7W8pVUA6P6wh7GxnfGJmyiY_A6hdGGI',
    appId: '1:1054221680598:ios:7bfed86b7d36edab6cae77',
    messagingSenderId: '1054221680598',
    projectId: 'yourturn-6c6b1',
    storageBucket: 'yourturn-6c6b1.firebasestorage.app',
    iosBundleId: 'com.example.yourturn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByhRadsvPQyqsnhqBMQG4aJNg9F05ePWM',
    appId: '1:1054221680598:web:c7287b0befb2ca916cae77',
    messagingSenderId: '1054221680598',
    projectId: 'yourturn-6c6b1',
    authDomain: 'yourturn-6c6b1.firebaseapp.com',
    storageBucket: 'yourturn-6c6b1.firebasestorage.app',
  );
}
